#!/usr/bin/perl

for ($i = 3;; $i++) {
 if(1 == ($i % 2) &&
    2 == ($i % 3) &&
    3 == ($i % 4) &&
    4 == ($i % 5)){
    #5 == ($i % 6)){
    #6 == ($i % 7)){
    #7 == ($i % 8)){
    #8 == ($i % 9)){ 
    #9 == ($i % 10)){
  print "$i\n";
  exit;
 }

}

#below easy explanation web pages url of this tool.
#http://contextwin.livedoor.blog/archives/5808849.html
